// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnjcoexivndpcmjapzbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuamNvZXhpdm5kcGNtamFwemJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2MTA2OTMsImV4cCI6MjA0OTE4NjY5M30.g-D8Uw3-EWFGfskFpUXVhfeoAdoziVuHCifHQx9pQ10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);